
  CREATE TABLE "SYSTEM"."USUARIO" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"EDAD" NUMBER(10,0) NOT NULL ENABLE, 
	"FECHA_REGISTRO" TIMESTAMP (6), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"TIPO_SANGRE" NUMBER(3,0) NOT NULL ENABLE, 
	 CHECK (tipo_sangre between 0 and 4) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;